	public DockerException(final Throwable cause) {
		super(calculateMessage(null, cause), cause);
	}

